version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "28000:8000"
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      RELOAD: "True"

  db:
    ports:
    - 25432:5432
    volumes:
    - dev-auo_project-db-data:/var/lib/postgresql/data


  celeryworker:
    volumes:
      # Adds current directory as volume.
    - .:/app/src/

  tusd:
    command: -base-path /files/ -behind-proxy -azure-blob-access-tier hot -azure-storage ${AZURE_STORAGE_CONTAINER} -azure-object-prefix tusd -hooks-enabled-events post-create,post-finish,post-terminate --hooks-http http://${BACKEND_HOST}:${BACKEND_PORT}/api/v1/hooks/tusd --hooks-http-retry 5 --hooks-http-backoff 2
    ports:
    - "21080:1080"


volumes:
  dev-auo_project-db-data:
    name: dev-auo_project-db-data
