from uuid import UUID

from pydantic import BaseModel, Field

from auo_project.models.measure_statistic_model import MeasureStatisticBase


class MeasureStatisticRead(MeasureStatisticBase):
    id: UUID


class MeasureStatisticCreate(MeasureStatisticBase):
    pass


class MeasureStatisticUpdate(MeasureStatisticBase):
    pass


class MeasureStatisticFlat(BaseModel):

    # statistics
    pass_rate_l_cu: float = Field(None, title="左寸通過率")
    pass_rate_l_qu: float = Field(None, title="左關通過率")
    pass_rate_l_ch: float = Field(None, title="左尺通過率")
    pass_rate_r_cu: float = Field(None, title="右寸通過率")
    pass_rate_r_qu: float = Field(None, title="右關通過率")
    pass_rate_r_ch: float = Field(None, title="右尺通過率")

    h1_l_cu: float = Field(None, title="左寸 h1")
    h1_l_qu: float = Field(None, title="左關 h1")
    h1_l_ch: float = Field(None, title="左尺 h1")
    h1_r_cu: float = Field(None, title="右寸 h1")
    h1_r_qu: float = Field(None, title="右關 h1")
    h1_r_ch: float = Field(None, title="右尺 h1")

    h1_div_t1_l_cu: float = Field(None, title="左寸 h1/t1")
    h1_div_t1_l_qu: float = Field(None, title="左關 h1/t1")
    h1_div_t1_l_ch: float = Field(None, title="左尺 h1/t1")
    h1_div_t1_r_cu: float = Field(None, title="右寸 h1/t1")
    h1_div_t1_r_qu: float = Field(None, title="右關 h1/t1")
    h1_div_t1_r_ch: float = Field(None, title="右尺 h1/t1")

    pr_l_cu: float = Field(None, title="左寸 pr")
    pr_l_qu: float = Field(None, title="左關 pr")
    pr_l_ch: float = Field(None, title="左尺 pr")
    pr_r_cu: float = Field(None, title="右寸 pr")
    pr_r_qu: float = Field(None, title="右關 pr")
    pr_r_ch: float = Field(None, title="右尺 pr")

    w1_l_cu: float = Field(None, title="左寸 w1")
    w1_l_qu: float = Field(None, title="左關 w1")
    w1_l_ch: float = Field(None, title="左尺 w1")
    w1_r_cu: float = Field(None, title="右寸 w1")
    w1_r_qu: float = Field(None, title="右關 w1")
    w1_r_ch: float = Field(None, title="右尺 w1")

    w1_div_t_l_cu: float = Field(None, title="左寸 w1/t1")
    w1_div_t_l_qu: float = Field(None, title="左關 w1/t1")
    w1_div_t_l_ch: float = Field(None, title="左尺 w1/t1")
    w1_div_t_r_cu: float = Field(None, title="右寸 w1/t1")
    w1_div_t_r_qu: float = Field(None, title="右關 w1/t1")
    w1_div_t_r_ch: float = Field(None, title="右尺 w1/t1")

    t1_div_t_l_cu: float = Field(None, title="左寸 t1/t")
    t1_div_t_l_qu: float = Field(None, title="左關 t1/t")
    t1_div_t_l_ch: float = Field(None, title="左尺 t1/t")
    t1_div_t_r_cu: float = Field(None, title="右寸 t1/t")
    t1_div_t_r_qu: float = Field(None, title="右關 t1/t")
    t1_div_t_r_ch: float = Field(None, title="右尺 t1/t")

    pw_l_cu: float = Field(None, title="左寸 pw")
    pw_l_qu: float = Field(None, title="左關 pw")
    pw_l_ch: float = Field(None, title="左尺 pw")
    pw_r_cu: float = Field(None, title="右寸 pw")
    pw_r_qu: float = Field(None, title="右關 pw")
    pw_r_ch: float = Field(None, title="右尺 pw")

    pwcv_l_cu: float = Field(None, title="左寸 pwcv")
    pwcv_l_qu: float = Field(None, title="左關 pwcv")
    pwcv_l_ch: float = Field(None, title="左尺 pwcv")
    pwcv_r_cu: float = Field(None, title="右寸 pwcv")
    pwcv_r_qu: float = Field(None, title="右關 pwcv")
    pwcv_r_ch: float = Field(None, title="右尺 pwcv")

    a0_l_cu: float = Field(None, title="左寸 a0")
    a0_l_qu: float = Field(None, title="左關 a0")
    a0_l_ch: float = Field(None, title="左尺 a0")
    a0_r_cu: float = Field(None, title="右寸 a0")
    a0_r_qu: float = Field(None, title="右關 a0")
    a0_r_ch: float = Field(None, title="右尺 a0")

    c1_l_cu: float = Field(None, title="左寸 c1")
    c1_l_qu: float = Field(None, title="左關 c1")
    c1_l_ch: float = Field(None, title="左尺 c1")
    c1_r_cu: float = Field(None, title="右寸 c1")
    c1_r_qu: float = Field(None, title="右關 c1")
    c1_r_ch: float = Field(None, title="右尺 c1")
    c2_l_cu: float = Field(None, title="左寸 c2")
    c2_l_qu: float = Field(None, title="左關 c2")
    c2_l_ch: float = Field(None, title="左尺 c2")
    c2_r_cu: float = Field(None, title="右寸 c2")
    c2_r_qu: float = Field(None, title="右關 c2")
    c2_r_ch: float = Field(None, title="右尺 c2")
    c3_l_cu: float = Field(None, title="左寸 c3")
    c3_l_qu: float = Field(None, title="左關 c3")
    c3_l_ch: float = Field(None, title="左尺 c3")
    c3_r_cu: float = Field(None, title="右寸 c3")
    c3_r_qu: float = Field(None, title="右關 c3")
    c3_r_ch: float = Field(None, title="右尺 c3")
    c4_l_cu: float = Field(None, title="左寸 c4")
    c4_l_qu: float = Field(None, title="左關 c4")
    c4_l_ch: float = Field(None, title="左尺 c4")
    c4_r_cu: float = Field(None, title="右寸 c4")
    c4_r_qu: float = Field(None, title="右關 c4")
    c4_r_ch: float = Field(None, title="右尺 c4")
    c5_l_cu: float = Field(None, title="左寸 c5")
    c5_l_qu: float = Field(None, title="左關 c5")
    c5_l_ch: float = Field(None, title="左尺 c5")
    c5_r_cu: float = Field(None, title="右寸 c5")
    c5_r_qu: float = Field(None, title="右關 c5")
    c5_r_ch: float = Field(None, title="右尺 c5")
    c6_l_cu: float = Field(None, title="左寸 c6")
    c6_l_qu: float = Field(None, title="左關 c6")
    c6_l_ch: float = Field(None, title="左尺 c6")
    c6_r_cu: float = Field(None, title="右寸 c6")
    c6_r_qu: float = Field(None, title="右關 c6")
    c6_r_ch: float = Field(None, title="右尺 c6")
    c7_l_cu: float = Field(None, title="左寸 c7")
    c7_l_qu: float = Field(None, title="左關 c7")
    c7_l_ch: float = Field(None, title="左尺 c7")
    c7_r_cu: float = Field(None, title="右寸 c7")
    c7_r_qu: float = Field(None, title="右關 c7")
    c7_r_ch: float = Field(None, title="右尺 c7")
    c8_l_cu: float = Field(None, title="左寸 c8")
    c8_l_qu: float = Field(None, title="左關 c8")
    c8_l_ch: float = Field(None, title="左尺 c8")
    c8_r_cu: float = Field(None, title="右寸 c8")
    c8_r_qu: float = Field(None, title="右關 c8")
    c8_r_ch: float = Field(None, title="右尺 c8")
    c9_l_cu: float = Field(None, title="左寸 c9")
    c9_l_qu: float = Field(None, title="左關 c9")
    c9_l_ch: float = Field(None, title="左尺 c9")
    c9_r_cu: float = Field(None, title="右寸 c9")
    c9_r_qu: float = Field(None, title="右關 c9")
    c9_r_ch: float = Field(None, title="右尺 c9")
    c10_l_cu: float = Field(None, title="左寸 c10")
    c10_l_qu: float = Field(None, title="左關 c10")
    c10_l_ch: float = Field(None, title="左尺 c10")
    c10_r_cu: float = Field(None, title="右寸 c10")
    c10_r_qu: float = Field(None, title="右關 c10")
    c10_r_ch: float = Field(None, title="右尺 c10")
    c11_l_cu: float = Field(None, title="左寸 c11")
    c11_l_qu: float = Field(None, title="左關 c11")
    c11_l_ch: float = Field(None, title="左尺 c11")
    c11_r_cu: float = Field(None, title="右寸 c11")
    c11_r_qu: float = Field(None, title="右關 c11")
    c11_r_ch: float = Field(None, title="右尺 c11")

    p1_l_cu: float = Field(None, title="左寸 p1")
    p1_l_qu: float = Field(None, title="左關 p1")
    p1_l_ch: float = Field(None, title="左尺 p1")
    p1_r_cu: float = Field(None, title="右寸 p1")
    p1_r_qu: float = Field(None, title="右關 p1")
    p1_r_ch: float = Field(None, title="右尺 p1")
    p2_l_cu: float = Field(None, title="左寸 p2")
    p2_l_qu: float = Field(None, title="左關 p2")
    p2_l_ch: float = Field(None, title="左尺 p2")
    p2_r_cu: float = Field(None, title="右寸 p2")
    p2_r_qu: float = Field(None, title="右關 p2")
    p2_r_ch: float = Field(None, title="右尺 p2")
    p3_l_cu: float = Field(None, title="左寸 p3")
    p3_l_qu: float = Field(None, title="左關 p3")
    p3_l_ch: float = Field(None, title="左尺 p3")
    p3_r_cu: float = Field(None, title="右寸 p3")
    p3_r_qu: float = Field(None, title="右關 p3")
    p3_r_ch: float = Field(None, title="右尺 p3")
    p4_l_cu: float = Field(None, title="左寸 p4")
    p4_l_qu: float = Field(None, title="左關 p4")
    p4_l_ch: float = Field(None, title="左尺 p4")
    p4_r_cu: float = Field(None, title="右寸 p4")
    p4_r_qu: float = Field(None, title="右關 p4")
    p4_r_ch: float = Field(None, title="右尺 p4")
    p5_l_cu: float = Field(None, title="左寸 p5")
    p5_l_qu: float = Field(None, title="左關 p5")
    p5_l_ch: float = Field(None, title="左尺 p5")
    p5_r_cu: float = Field(None, title="右寸 p5")
    p5_r_qu: float = Field(None, title="右關 p5")
    p5_r_ch: float = Field(None, title="右尺 p5")
    p6_l_cu: float = Field(None, title="左寸 p6")
    p6_l_qu: float = Field(None, title="左關 p6")
    p6_l_ch: float = Field(None, title="左尺 p6")
    p6_r_cu: float = Field(None, title="右寸 p6")
    p6_r_qu: float = Field(None, title="右關 p6")
    p6_r_ch: float = Field(None, title="右尺 p6")
    p7_l_cu: float = Field(None, title="左寸 p7")
    p7_l_qu: float = Field(None, title="左關 p7")
    p7_l_ch: float = Field(None, title="左尺 p7")
    p7_r_cu: float = Field(None, title="右寸 p7")
    p7_r_qu: float = Field(None, title="右關 p7")
    p7_r_ch: float = Field(None, title="右尺 p7")
    p8_l_cu: float = Field(None, title="左寸 p8")
    p8_l_qu: float = Field(None, title="左關 p8")
    p8_l_ch: float = Field(None, title="左尺 p8")
    p8_r_cu: float = Field(None, title="右寸 p8")
    p8_r_qu: float = Field(None, title="右關 p8")
    p8_r_ch: float = Field(None, title="右尺 p8")
    p9_l_cu: float = Field(None, title="左寸 p9")
    p9_l_qu: float = Field(None, title="左關 p9")
    p9_l_ch: float = Field(None, title="左尺 p9")
    p9_r_cu: float = Field(None, title="右寸 p9")
    p9_r_qu: float = Field(None, title="右關 p9")
    p9_r_ch: float = Field(None, title="右尺 p9")
    p10_l_cu: float = Field(None, title="左寸 p10")
    p10_l_qu: float = Field(None, title="左關 p10")
    p10_l_ch: float = Field(None, title="左尺 p10")
    p10_r_cu: float = Field(None, title="右寸 p10")
    p10_r_qu: float = Field(None, title="右關 p10")
    p10_r_ch: float = Field(None, title="右尺 p10")
    p11_l_cu: float = Field(None, title="左寸 p11")
    p11_l_qu: float = Field(None, title="左關 p11")
    p11_l_ch: float = Field(None, title="左尺 p11")
    p11_r_cu: float = Field(None, title="右寸 p11")
    p11_r_qu: float = Field(None, title="右關 p11")
    p11_r_ch: float = Field(None, title="右尺 p11")
